### PR TITLE
Add the 'checksum' and 'completed' attributes to private ERDDAP config

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
@lukecampbell any comments?

**Comment by lukecampbell** [comment]
Let me try this out on staging.

**Comment by kwilcox** [comment]
@lukecampbell is this deployed?

**Comment by lukecampbell** [comment]
yes

**Comment by kwilcox** [comment]
@lukecampbell Thanks! I see if on most deployments, but it is missing from these four (through ERDDAP)

* `SG609-20140719T1700`
* `SG609-20150206T1720`
* `SG610-20140715T1400`
* `SG610-20150206T1750`

**Comment by lukecampbell** [comment]
Ok, looks like I need to add a cron job to update deployments where folks upload files via FTP.

**Pull request merged**
